/**
 * Cloudflare Worker entry.
 *
 * Same handler as the Node entry (app.ts), on the SDK's Web-standard Streamable
 * HTTP transport in stateless mode, so nothing has to survive between isolates.
 *
 * Auth today: the same shared bearer token (MCP_TOKEN secret) as local dev.
 * The intended production auth is OAuth via @cloudflare/workers-oauth-provider so
 * Claude and ChatGPT can connect as custom connectors — the hook is marked below
 * and the wiring is described in README.md ("Workers and OAuth"). It is NOT wired:
 * there is no OAuth flow here, faked or otherwise.
 *
 * Build note: `npm run build:ui` copies the ext-apps browser bundle into
 * src/generated/ so wrangler can inline it as a Text module (see wrangler.toml).
 */
import { bearerTokenAuth, createFetchHandler } from './app.js';
// Generated by scripts/build-ui.mjs (gitignored). Wrangler loads *.txt as a string module.
import extAppsBundleJs from './generated/ext-apps-bundle.txt';

export interface Env {
  REGISTRY_URL: string;
  REGISTRY_TOKEN?: string;
  CF_ACCESS_CLIENT_ID?: string;
  CF_ACCESS_CLIENT_SECRET?: string;
  MCP_TOKEN?: string;
  MCP_PATH?: string;
}

function handlerFor(env: Env) {
  return createFetchHandler(
    {
      registryUrl: env.REGISTRY_URL,
      registryToken: env.REGISTRY_TOKEN,
      cfAccessClientId: env.CF_ACCESS_CLIENT_ID,
      cfAccessClientSecret: env.CF_ACCESS_CLIENT_SECRET,
      mcpToken: env.MCP_TOKEN,
      mcpPath: env.MCP_PATH ?? '/mcp',
      extAppsBundleJs,
    },
    // ---- OAUTH HOOK ----------------------------------------------------------
    // When @cloudflare/workers-oauth-provider is wired, the provider wraps this
    // Worker and has already validated the access token by the time the request
    // reaches the API handler; replace bearerTokenAuth with a check that trusts
    // the provider's `ctx.props` (the authenticated user) instead. See README.md.
    bearerTokenAuth(env.MCP_TOKEN)
    // -------------------------------------------------------------------------
  );
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    return handlerFor(env)(request);
  },
};
