/**
 * Cloudflare Worker entry.
 *
 * Same handler as the Node entry (app.ts), on the SDK's Web-standard Streamable
 * HTTP transport in stateless mode, so nothing has to survive between isolates.
 *
 * Auth: OAuth 2.1 via @cloudflare/workers-oauth-provider, so Claude and ChatGPT
 * connect as custom connectors with the bare URL. The provider answers discovery
 * (/.well-known/*), Dynamic Client Registration (/oauth/register) and the token
 * endpoint (/oauth/token); src/oauth.ts is the sign-in page at /authorize. By the
 * time a request reaches the API handler on /mcp the provider has validated its
 * access token; the AuthCheck below only confirms the token was issued to FtB.
 * The Node entry (node.ts) keeps the shared bearer token for local dev.
 *
 * Build note: `npm run build:ui` copies the ext-apps browser bundle into
 * src/generated/ so wrangler can inline it as a Text module (see wrangler.toml).
 */
import { OAuthProvider, type OAuthHelpers } from '@cloudflare/workers-oauth-provider';
import type { ExecutionContext, KVNamespace } from '@cloudflare/workers-types';

import { createFetchHandler, type AuthCheck } from './app.js';
import { FTB_USER_ID, oauthHandler, SCOPES, type FtbProps } from './oauth.js';
// Generated by scripts/build-ui.mjs (gitignored). Wrangler loads *.txt as a string module.
import extAppsBundleJs from './generated/ext-apps-bundle.txt';

export interface Env {
  REGISTRY_URL: string;
  REGISTRY_TOKEN?: string;
  CF_ACCESS_CLIENT_ID?: string;
  CF_ACCESS_CLIENT_SECRET?: string;
  /** The password the /authorize sign-in page asks for. Unset = no token is ever issued. */
  MCP_TOKEN?: string;
  /** Clients, grants and hashed tokens (wrangler.toml [[kv_namespaces]]). */
  OAUTH_KV: KVNamespace;
  /** Injected by the provider into both handlers. */
  OAUTH_PROVIDER: OAuthHelpers;
}

/** Fixed: the provider's apiRoute and the handler's path have to agree. */
const MCP_PATH = '/mcp';

/** The provider has already validated the access token; this checks whose it is. */
function ftbOnly(props: Partial<FtbProps> | undefined): AuthCheck {
  return () =>
    props?.userId === FTB_USER_ID
      ? null
      : new Response(JSON.stringify({ error: 'forbidden', detail: 'This access token was not issued to FtB.' }), {
          status: 403,
          headers: { 'content-type': 'application/json' },
        });
}

function handlerFor(env: Env, props: Partial<FtbProps> | undefined) {
  return createFetchHandler(
    {
      registryUrl: env.REGISTRY_URL,
      registryToken: env.REGISTRY_TOKEN,
      cfAccessClientId: env.CF_ACCESS_CLIENT_ID,
      cfAccessClientSecret: env.CF_ACCESS_CLIENT_SECRET,
      mcpPath: MCP_PATH,
      extAppsBundleJs,
    },
    ftbOnly(props)
  );
}

export default new OAuthProvider<Env>({
  apiRoute: MCP_PATH,
  apiHandler: {
    fetch: (request: Request, env: Env, ctx: ExecutionContext<Partial<FtbProps>>) => handlerFor(env, ctx.props)(request),
  },
  defaultHandler: oauthHandler,
  authorizeEndpoint: '/authorize',
  tokenEndpoint: '/oauth/token',
  clientRegistrationEndpoint: '/oauth/register',
  scopesSupported: SCOPES,
});
